// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Bq_cpp
double Bq_cpp(arma::vec theta);
RcppExport SEXP _vMFglm_Bq_cpp(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Bq_cpp(theta));
    return rcpp_result_gen;
END_RCPP
}
// Hq_cpp
double Hq_cpp(arma::vec theta);
RcppExport SEXP _vMFglm_Hq_cpp(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Hq_cpp(theta));
    return rcpp_result_gen;
END_RCPP
}
// Cq_cpp
double Cq_cpp(arma::vec theta, bool logarithm);
RcppExport SEXP _vMFglm_Cq_cpp(SEXP thetaSEXP, SEXP logarithmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< bool >::type logarithm(logarithmSEXP);
    rcpp_result_gen = Rcpp::wrap(Cq_cpp(theta, logarithm));
    return rcpp_result_gen;
END_RCPP
}
// b1_vMF
arma::vec b1_vMF(arma::vec theta);
RcppExport SEXP _vMFglm_b1_vMF(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(b1_vMF(theta));
    return rcpp_result_gen;
END_RCPP
}
// b2_vMF
arma::mat b2_vMF(arma::vec theta);
RcppExport SEXP _vMFglm_b2_vMF(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(b2_vMF(theta));
    return rcpp_result_gen;
END_RCPP
}
// diag_matrix
arma::mat diag_matrix(const arma::mat& X, double lambda);
RcppExport SEXP _vMFglm_diag_matrix(SEXP XSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(diag_matrix(X, lambda));
    return rcpp_result_gen;
END_RCPP
}
// calculate_b1_vMF
arma::mat calculate_b1_vMF(const arma::mat& Offset, const Rcpp::List& Xt_list, const arma::vec& beta, int n);
RcppExport SEXP _vMFglm_calculate_b1_vMF(SEXP OffsetSEXP, SEXP Xt_listSEXP, SEXP betaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Offset(OffsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Xt_list(Xt_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_b1_vMF(Offset, Xt_list, beta, n));
    return rcpp_result_gen;
END_RCPP
}
// calculate_b2_vMF
arma::mat calculate_b2_vMF(const arma::mat& Offset, const Rcpp::List& Xt_list, const arma::vec& beta, int n);
RcppExport SEXP _vMFglm_calculate_b2_vMF(SEXP OffsetSEXP, SEXP Xt_listSEXP, SEXP betaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Offset(OffsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Xt_list(Xt_listSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_b2_vMF(Offset, Xt_list, beta, n));
    return rcpp_result_gen;
END_RCPP
}
// vMFglm_iteration_FixedGamma
List vMFglm_iteration_FixedGamma(arma::mat X, arma::mat Y, arma::mat Offset, arma::vec beta, arma::mat Xt, List Xt_list, double eps, int maxit, double lambda, bool orthogonal, arma::vec gamma, Rcpp::Nullable<Rcpp::IntegerVector> zero_beta, bool verbose);
RcppExport SEXP _vMFglm_vMFglm_iteration_FixedGamma(SEXP XSEXP, SEXP YSEXP, SEXP OffsetSEXP, SEXP betaSEXP, SEXP XtSEXP, SEXP Xt_listSEXP, SEXP epsSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP orthogonalSEXP, SEXP gammaSEXP, SEXP zero_betaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Offset(OffsetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< List >::type Xt_list(Xt_listSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type orthogonal(orthogonalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type zero_beta(zero_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(vMFglm_iteration_FixedGamma(X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sphereGLM_iteration_KKT
List sphereGLM_iteration_KKT(arma::mat X, arma::mat Y, arma::mat Offset, arma::vec mu, arma::vec beta, arma::mat Xt, List Xt_list, double eps, int maxit, double lambda);
RcppExport SEXP _vMFglm_sphereGLM_iteration_KKT(SEXP XSEXP, SEXP YSEXP, SEXP OffsetSEXP, SEXP muSEXP, SEXP betaSEXP, SEXP XtSEXP, SEXP Xt_listSEXP, SEXP epsSEXP, SEXP maxitSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Offset(OffsetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< List >::type Xt_list(Xt_listSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(sphereGLM_iteration_KKT(X, Y, Offset, mu, beta, Xt, Xt_list, eps, maxit, lambda));
    return rcpp_result_gen;
END_RCPP
}
// vMFglm_iteration_FixedGamma_fast
List vMFglm_iteration_FixedGamma_fast(arma::mat X, arma::mat Y, arma::mat Offset, arma::vec beta, arma::mat Xt, List Xt_list, double eps, int maxit, double lambda, bool orthogonal, arma::vec gamma, Rcpp::Nullable<Rcpp::IntegerVector> zero_beta, bool verbose, std::string method, double kappa_max);
RcppExport SEXP _vMFglm_vMFglm_iteration_FixedGamma_fast(SEXP XSEXP, SEXP YSEXP, SEXP OffsetSEXP, SEXP betaSEXP, SEXP XtSEXP, SEXP Xt_listSEXP, SEXP epsSEXP, SEXP maxitSEXP, SEXP lambdaSEXP, SEXP orthogonalSEXP, SEXP gammaSEXP, SEXP zero_betaSEXP, SEXP verboseSEXP, SEXP methodSEXP, SEXP kappa_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Offset(OffsetSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xt(XtSEXP);
    Rcpp::traits::input_parameter< List >::type Xt_list(Xt_listSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type orthogonal(orthogonalSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type zero_beta(zero_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type kappa_max(kappa_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(vMFglm_iteration_FixedGamma_fast(X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta, verbose, method, kappa_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vMFglm_Bq_cpp", (DL_FUNC) &_vMFglm_Bq_cpp, 1},
    {"_vMFglm_Hq_cpp", (DL_FUNC) &_vMFglm_Hq_cpp, 1},
    {"_vMFglm_Cq_cpp", (DL_FUNC) &_vMFglm_Cq_cpp, 2},
    {"_vMFglm_b1_vMF", (DL_FUNC) &_vMFglm_b1_vMF, 1},
    {"_vMFglm_b2_vMF", (DL_FUNC) &_vMFglm_b2_vMF, 1},
    {"_vMFglm_diag_matrix", (DL_FUNC) &_vMFglm_diag_matrix, 2},
    {"_vMFglm_calculate_b1_vMF", (DL_FUNC) &_vMFglm_calculate_b1_vMF, 4},
    {"_vMFglm_calculate_b2_vMF", (DL_FUNC) &_vMFglm_calculate_b2_vMF, 4},
    {"_vMFglm_vMFglm_iteration_FixedGamma", (DL_FUNC) &_vMFglm_vMFglm_iteration_FixedGamma, 13},
    {"_vMFglm_sphereGLM_iteration_KKT", (DL_FUNC) &_vMFglm_sphereGLM_iteration_KKT, 10},
    {"_vMFglm_vMFglm_iteration_FixedGamma_fast", (DL_FUNC) &_vMFglm_vMFglm_iteration_FixedGamma_fast, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_vMFglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
