# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Bq_cpp <- function(theta) {
    .Call('_vMFglm_Bq_cpp', PACKAGE = 'vMFglm', theta)
}

Hq_cpp <- function(theta) {
    .Call('_vMFglm_Hq_cpp', PACKAGE = 'vMFglm', theta)
}

Cq_cpp <- function(theta, logarithm = TRUE) {
    .Call('_vMFglm_Cq_cpp', PACKAGE = 'vMFglm', theta, logarithm)
}

b1_vMF <- function(theta) {
    .Call('_vMFglm_b1_vMF', PACKAGE = 'vMFglm', theta)
}

b2_vMF <- function(theta) {
    .Call('_vMFglm_b2_vMF', PACKAGE = 'vMFglm', theta)
}

diag_matrix <- function(X, lambda) {
    .Call('_vMFglm_diag_matrix', PACKAGE = 'vMFglm', X, lambda)
}

calculate_b1_vMF <- function(Offset, Xt_list, beta, n) {
    .Call('_vMFglm_calculate_b1_vMF', PACKAGE = 'vMFglm', Offset, Xt_list, beta, n)
}

calculate_b2_vMF <- function(Offset, Xt_list, beta, n) {
    .Call('_vMFglm_calculate_b2_vMF', PACKAGE = 'vMFglm', Offset, Xt_list, beta, n)
}

vMFglm_iteration_FixedGamma <- function(X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta = NULL, verbose = FALSE) {
    .Call('_vMFglm_vMFglm_iteration_FixedGamma', PACKAGE = 'vMFglm', X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta, verbose)
}

sphereGLM_iteration_KKT <- function(X, Y, Offset, mu, beta, Xt, Xt_list, eps, maxit, lambda) {
    .Call('_vMFglm_sphereGLM_iteration_KKT', PACKAGE = 'vMFglm', X, Y, Offset, mu, beta, Xt, Xt_list, eps, maxit, lambda)
}

vMFglm_iteration_FixedGamma_fast <- function(X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta = NULL, verbose = FALSE, method = "newton", kappa_max = 1e6) {
    .Call('_vMFglm_vMFglm_iteration_FixedGamma_fast', PACKAGE = 'vMFglm', X, Y, Offset, beta, Xt, Xt_list, eps, maxit, lambda, orthogonal, gamma, zero_beta, verbose, method, kappa_max)
}

